// Committee glossary and department → committee mappings.
// Tokyo: /outline/jurisdiction.html. Shibuya: /about/2023021000185/. Suginami and the other wards name the
// committee per bill.
// English names are our own unofficial translations; never let the LLM translate these.

/** @type {Record<string, string>} */
export const committeeEn = {
	総務委員会: 'General Affairs Committee',
	財政委員会: 'Finance Committee',
	文教委員会: 'Education and Culture Committee',
	都市整備委員会: 'Urban Development Committee',
	厚生委員会: 'Health and Welfare Committee',
	'経済・港湾委員会': 'Economy and Port Committee',
	'環境・建設委員会': 'Environment and Construction Committee',
	公営企業委員会: 'Public Enterprise Committee',
	'警察・消防委員会': 'Police and Fire Committee',
	都市環境委員会: 'Urban Environment Committee',
	区民福祉委員会: 'Residents and Welfare Committee',
	総務財政委員会: 'General Affairs and Finance Committee',
	区民生活委員会: 'Residents Life Committee',
	保健福祉委員会: 'Health and Welfare Committee',
	// 23 wards, standing committees (some wards add 常任 to the name)
	総務常任委員会: 'General Affairs Committee',
	企画総務委員会: 'Planning and General Affairs Committee',
	企画総務常任委員会: 'Planning and General Affairs Committee',
	区民委員会: 'Residents Committee',
	区民生活常任委員会: 'Residents Life Committee',
	区民文教委員会: 'Residents, Education and Culture Committee',
	区民文教常任委員会: 'Residents, Education and Culture Committee',
	保健福祉常任委員会: 'Health and Welfare Committee',
	福祉保健常任委員会: 'Welfare and Health Committee',
	福祉健康委員会: 'Welfare and Health Committee',
	文教常任委員会: 'Education and Culture Committee',
	子ども文教委員会: 'Children, Education and Culture Committee',
	建設委員会: 'Construction Committee',
	建設常任委員会: 'Construction Committee',
	建設環境委員会: 'Construction and Environment Committee',
	都市整備常任委員会: 'Urban Development Committee',
	産業環境委員会: 'Industry and Environment Committee',
	産業建設委員会: 'Industry and Construction Committee',
	地域産業都市委員会: 'Community, Industry and Urban Development Committee',
	生活振興環境委員会: 'Community Life and Environment Committee',
	地域産業委員会: 'Community and Industry Committee',
	健康福祉委員会: 'Health and Welfare Committee',
	まちづくり環境委員会: 'Urban Development and Environment Committee',
	こども文教委員会: 'Children, Education and Culture Committee',
	// Tama area, standing committees
	健康福祉常任委員会: 'Health and Welfare Committee',
	文教社会常任委員会: 'Education and Community Committee',
	福祉文教委員会: 'Welfare and Education Committee',
	環境建設委員会: 'Environment and Construction Committee',
	総務企画委員会: 'General Affairs and Planning Committee',
	環境まちづくり委員会: 'Environment and Community Development Committee',
	// 23 wards, special committees
	予算特別委員会: 'Special Committee on the Budget',
	決算特別委員会: 'Special Committee on the Accounts',
	'子育て・若者支援特別委員会': 'Special Committee on Child-Rearing and Youth Support',
	'子ども・若者施策推進特別委員会': 'Special Committee on Children and Youth Policy',
	子ども若者支援・共生社会推進特別委員会: 'Special Committee on Children, Youth and an Inclusive Society',
	'文化・観光特別委員会': 'Special Committee on Culture and Tourism',
	'交通対策・地区整備特別委員会': 'Special Committee on Transport and District Development',
	'環境・安全安心特別委員会': 'Special Committee on the Environment and Public Safety',
	'環境・清掃・リサイクル対策等特別委員会': 'Special Committee on the Environment, Waste and Recycling',
	地域交通政策推進特別委員会: 'Special Committee on Local Transport Policy',
	危機管理対策特別委員会: 'Special Committee on Crisis Management',
	'災害・防犯・オウム問題対策等特別委員会': 'Special Committee on Disasters, Crime Prevention and the Aum Issue',
	'DX・地域行政・公共施設整備等推進特別委員会': 'Special Committee on DX, Local Administration and Public Facilities',
	'SDGs推進・行財政改革特別委員会': 'Special Committee on the SDGs and Administrative Reform',
	'まちづくり・公共交通推進特別委員会': 'Special Committee on Community Development and Public Transport'
};

/** @type {Record<string, Record<string, string>>} assembly id → department → committee */
export const committeeByDepartment = {
	tokyo: {
		政策企画局: '総務委員会',
		子供政策連携室: '総務委員会',
		総務局: '総務委員会',
		デジタルサービス局: '総務委員会',
		人事委員会: '総務委員会',
		選挙管理委員会: '総務委員会',
		監査委員: '総務委員会',
		財務局: '財政委員会',
		主税局: '財政委員会',
		会計管理局: '財政委員会',
		収用委員会: '財政委員会',
		生活文化局: '文教委員会',
		都民安全総合対策本部: '文教委員会',
		スポーツ推進本部: '文教委員会',
		教育委員会: '文教委員会',
		教育庁: '文教委員会',
		都市整備局: '都市整備委員会',
		住宅政策本部: '都市整備委員会',
		福祉局: '厚生委員会',
		保健医療局: '厚生委員会',
		産業労働局: '経済・港湾委員会',
		中央卸売市場: '経済・港湾委員会',
		スタートアップ戦略推進本部: '経済・港湾委員会',
		港湾局: '経済・港湾委員会',
		労働委員会: '経済・港湾委員会',
		環境局: '環境・建設委員会',
		建設局: '環境・建設委員会',
		交通局: '公営企業委員会',
		水道局: '公営企業委員会',
		下水道局: '公営企業委員会',
		公安委員会: '警察・消防委員会',
		警視庁: '警察・消防委員会',
		東京消防庁: '警察・消防委員会'
	},
	'tokyo/shibuya': {
		経営企画部: '総務委員会',
		デジタルサービス部: '総務委員会',
		総務部: '総務委員会',
		危機管理対策部: '総務委員会',
		会計管理室: '総務委員会',
		産業観光文化部: '都市環境委員会',
		都市整備部: '都市環境委員会',
		まちづくり推進部: '都市環境委員会',
		土木部: '都市環境委員会',
		環境政策部: '都市環境委員会',
		学びとスポーツ部: '文教委員会',
		子ども家庭部: '文教委員会',
		教育委員会: '文教委員会',
		区民部: '区民福祉委員会',
		福祉部: '区民福祉委員会',
		健康推進部: '区民福祉委員会'
	}
};
