// The 47 prefectures: [name, kana, English]. Kana is what people type on a phone. The search lists
// only those in SEARCH_PREFECTURES (config/site.js).
/** @type {[string, string, string][]} */
export const prefectures = [
	['北海道', 'ほっかいどう', 'Hokkaido'],
	['青森県', 'あおもりけん', 'Aomori'],
	['岩手県', 'いわてけん', 'Iwate'],
	['宮城県', 'みやぎけん', 'Miyagi'],
	['秋田県', 'あきたけん', 'Akita'],
	['山形県', 'やまがたけん', 'Yamagata'],
	['福島県', 'ふくしまけん', 'Fukushima'],
	['茨城県', 'いばらきけん', 'Ibaraki'],
	['栃木県', 'とちぎけん', 'Tochigi'],
	['群馬県', 'ぐんまけん', 'Gunma'],
	['埼玉県', 'さいたまけん', 'Saitama'],
	['千葉県', 'ちばけん', 'Chiba'],
	['東京都', 'とうきょうと', 'Tokyo'],
	['神奈川県', 'かながわけん', 'Kanagawa'],
	['新潟県', 'にいがたけん', 'Niigata'],
	['富山県', 'とやまけん', 'Toyama'],
	['石川県', 'いしかわけん', 'Ishikawa'],
	['福井県', 'ふくいけん', 'Fukui'],
	['山梨県', 'やまなしけん', 'Yamanashi'],
	['長野県', 'ながのけん', 'Nagano'],
	['岐阜県', 'ぎふけん', 'Gifu'],
	['静岡県', 'しずおかけん', 'Shizuoka'],
	['愛知県', 'あいちけん', 'Aichi'],
	['三重県', 'みえけん', 'Mie'],
	['滋賀県', 'しがけん', 'Shiga'],
	['京都府', 'きょうとふ', 'Kyoto'],
	['大阪府', 'おおさかふ', 'Osaka'],
	['兵庫県', 'ひょうごけん', 'Hyogo'],
	['奈良県', 'ならけん', 'Nara'],
	['和歌山県', 'わかやまけん', 'Wakayama'],
	['鳥取県', 'とっとりけん', 'Tottori'],
	['島根県', 'しまねけん', 'Shimane'],
	['岡山県', 'おかやまけん', 'Okayama'],
	['広島県', 'ひろしまけん', 'Hiroshima'],
	['山口県', 'やまぐちけん', 'Yamaguchi'],
	['徳島県', 'とくしまけん', 'Tokushima'],
	['香川県', 'かがわけん', 'Kagawa'],
	['愛媛県', 'えひめけん', 'Ehime'],
	['高知県', 'こうちけん', 'Kochi'],
	['福岡県', 'ふくおかけん', 'Fukuoka'],
	['佐賀県', 'さがけん', 'Saga'],
	['長崎県', 'ながさきけん', 'Nagasaki'],
	['熊本県', 'くまもとけん', 'Kumamoto'],
	['大分県', 'おおいたけん', 'Oita'],
	['宮崎県', 'みやざきけん', 'Miyazaki'],
	['鹿児島県', 'かごしまけん', 'Kagoshima'],
	['沖縄県', 'おきなわけん', 'Okinawa']
];
